version: '3.8'

services:
  theadmiral-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - theadmiral-db
    environment:
      DATABASE_URL: "postgresql://user:pass@theadmiral-db:5432/trading_db"
    volumes:
      - .:/app

  theadmiral-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: trading_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-gui:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8082:8978" # שיניתי ל-8082 כדי למנוע התנגשויות
    depends_on:
      - theadmiral-db

volumes:
  pgdata: